
 services:
  db:
    container_name: postgresdb
    image: postgres:16-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  
  metaverse_magna_backend:
    depends_on:
      - db
    container_name: metaverse_magna_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:${PORT}
      - 5000:5000
    env_file: .env
    environment:
      - PORT=${PORT}